language: python

python:
    - "3.6"

services: 
    - postgresql
    
before_script:
    - psql -c 'create database ah_zeus_db;' -U postgres
    
install:
    - pip install -r requirements.txt

script:
    - coverage run --source='authors' manage.py test

after_success:
    - coveralls
